# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_17_X64)"
      echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME_17_X64)\bin;$(PATH)"

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      wget https://mirrors.estointernet.in/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
      tar -xvf apache-maven-3.6.3-bin.tar.gz
      mv apache-maven-3.6.3 /opt/
      mvn -version
      mvn package


